In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/nirupamchakraborty/Desktop/complete-python/venv/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nirupamchakraborty/Desktop/complete-python/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/nirupamchakraborty/Desktop/complete-python/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 4.9 MB/s  0:00:02 eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.


Pandas-DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
 import pandas as pd

In [3]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data =[1,2,3]
index=['a','b','c']
pd.Series(data, index=index)

a    1
b    2
c    3
dtype: int64

In [11]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    "Name": ["Krish", "John", "Pratik"],
    "Age":[97,98,99],
    "City":["Pune", "Banglore", "Delhi"]
}

df= pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0   Krish   97      Pune
1    John   98  Banglore
2  Pratik   99     Delhi
<class 'pandas.DataFrame'>

In [10]:
# we can canvet it to numpy array
import numpy as np
np.array(df)

array([['Krish', 97, 'Pune'],
       ['John', 98, 'Banglore'],
       ['Pratik', 99, 'Delhi']], dtype=object)

In [22]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]

df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

In [18]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [19]:

df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [23]:
### Accessing Data From Dataframe
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [26]:
df['Name']
# print(type(df['Name'])) #<class 'pandas.Series'>

0    Krish
1     John
2    Bappy
3     JAck
Name: Name, dtype: str

In [27]:
df.loc[0] # 1st row

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [29]:
df.iloc[0] #index location = 0

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [32]:
# df.iloc[0][1]

KeyError: 2

In [34]:
## Accessing a specified element
df.at[1,'Age']

np.int64(34)